

# Pull base image (WV)
FROM tomcat:8
# RUN apt-get install wget

# Pull base image (NV)
# FROM tomcat:9.0.55-jdk17-corretto


# Package (WV)
# RUN yum install -y ??



# Package (NV)
# RUN yum install -y wget-1.14





