name: Github Actions Example

on:
  [push]

jobs:
  test:
    name: Snyk test
    runs-on: nginx-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Build image
      run:
      
      
    - name: Snyk container scan
      continue-on-error: true
      uses: 
      env:
        DEBUG: true
        SNYK_TOKEN: 
        
    - name: 
